# Site settings
title: Xuecheng Wang
email: wxcchuck@hotmail.com
description: Professional work, personal interests and more
url: https://wangxuecheng.com
baseurl: ""
github_username: wxcchuck
linkedin_username: xuechengwang

# Building settings
theme: minima
plugins: 
- jekyll-feed
